### ISSUE TITLE
Problema con il plugin sphinx_markdown_tables

### ISSUE THREAD

**Issue by gbvitrano** [gbvitrano/HfcQGIS#53]
Oggi li plugin è stato aggiornato, a noi  causa problemi.
Impedisce la compilazione.

```
Running Sphinx v1.7.6
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/hfcqgis-test/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hfcqgis-test/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hfcqgis-test/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hfcqgis-test/envs/latest/local/lib/python2.7/site-packages/sphinx/registry.py", line 326, in load_extension
    metadata = mod.setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hfcqgis-test/envs/latest/local/lib/python2.7/site-packages/sphinx_markdown_tables.py", line 8, in setup
    return {'version': __version__}
NameError: global name '__version__' is not defined

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/hfcqgis-test/envs/latest/local/lib/python2.7/site-packages/sphinx_markdown_tables.py", line 8, in setup
    return {'version': __version__}
NameError: global name '__version__' is not defined
The full traceback has been saved in /tmp/sphinx-err-IfDN5F.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by gbvitrano** [comment]
![screenshot_2018-07-28 hfcqgis-test read the docs](https://user-images.githubusercontent.com/20488693/43356597-cd98bf8a-9273-11e8-9909-cbb69f5ad9c6.png)

Disattivando dal conf.py il plugin, la compilazione torna a funzionare

Da: 
`extensions = ['sphinx.ext.ifconfig','sphinx_markdown_tables']`
a: 
`extensions = ['sphinx.ext.ifconfig']`

il problema è che nella guida possono essere presnti nei vari file .md tabelle in markdown che non vengono più covertite

ho provato ad usare il codice rst per le tabelle nel file .md  ma non funzionana 

![screenshot_2018-07-28 lpad](https://user-images.githubusercontent.com/20488693/43356620-5aae2748-9274-11e8-89c4-bc5e79e35a77.png)

@aborruso quando hai tempo puoi controllare per favore :-)

**Comment by pigreco** [comment]
ecco issues sul problema, ma non vedo la soluzione

https://github.com/ryanfox/sphinx-markdown-tables/issues/8

**Comment by aborruso** [comment]
Al momento ci sono problemi con la versione più recente. Ma prima funzionava.

Quindi per il momento ho forzato la versione precedente, che è la 0.0.6 https://github.com/gbvitrano/HfcQGIS/blob/master/requirements.txt#L4
